//INTEGRANTES:

//Guillén Mirabá José Felipe    
//Quimis Mendoza Jonathan Andy
//Victor Hugo Varas Roca

//CURSO:
//2-2

package batalla.de.acorazados;



import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JPanel;
import javax.swing.JTextArea;


public class VentanaJuego extends javax.swing.JFrame {
    public static JTextArea area;
    public static JPanel mar;
    public VentanaJuego() {
        initComponents();
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        panel_instrucciones.setBackground(Color.LIGHT_GRAY);
        panel_instrucciones.setLayout(new FlowLayout(FlowLayout.LEFT,0,0));
        panel_instrucciones.setPreferredSize(new Dimension(300,300));
        area=new JTextArea();
        area.setBorder(null);
        panel_instrucciones.add(area);
        area.setVisible(true);
        presentacion();
        panelJuego.setLayout(new FlowLayout(FlowLayout.LEFT,0,0));
        mar=new MarInicio();
        panelJuego.add(mar);
        setResizable(false);
    }
    public void presentacion(){
    panel_instrucciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "INSTRUCCIONES :"));
    panel_instrucciones.setBackground(Color.LIGHT_GRAY);
    area.setBackground(Color.LIGHT_GRAY);
    area.setForeground(Color.BLACK);
    area.setText("                      ! Batalla De Acorazados !"+"\n"+"\n"+"\n"+
        "- Haz click sobre la casilla donde quieres ubicar "+"\n"+
        " cada uno de tus barcos, tienes 5 en total."+"\n"+"\n"+
        "- Cuando hayas terminado de ubicar tus barcos"+"\n"+
        " presiona el boton (Listo!) para comenzar."+"\n"+"\n"+
        "- Una vez empiece el juego debes hacer click"+"\n"+
        " en la casilla que vas a atacar."+"\n"+"\n"+
        "- Jugarás contra la computadora la cual responderá"+"\n"+
        " inmediantamente cada ataque."+"\n"+"\n"+
        "- Los resultados de cada turno se mostrarán en"+"\n"+
        "esta consola."
        );
        area.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_instrucciones = new javax.swing.JPanel();
        panelJuego = new javax.swing.JPanel();
        RUBTN = new javax.swing.JButton();
        listoBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_instrucciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "INSTRUCCIONES :"));

        javax.swing.GroupLayout panel_instruccionesLayout = new javax.swing.GroupLayout(panel_instrucciones);
        panel_instrucciones.setLayout(panel_instruccionesLayout);
        panel_instruccionesLayout.setHorizontalGroup(
            panel_instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        panel_instruccionesLayout.setVerticalGroup(
            panel_instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        panelJuego.setPreferredSize(new java.awt.Dimension(550, 660));

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        RUBTN.setText("Reubicar");
        RUBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUBTNActionPerformed(evt);
            }
        });

        listoBTN.setText("Listo !");
        listoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel1.setText("INTEGRANTES:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Guillén Mirabá José Felipe");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Quimis Mendoza Jonathan Andy");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Varas Roca Victor Hugo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RUBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(listoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(panel_instrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(35, 35, 35)
                .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panel_instrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(RUBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RUBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUBTNActionPerformed
    RUBTN.setText("Reubicar");
    panelJuego.remove(mar);
    panelJuego.setVisible(false);
    mar=new MarInicio();
    mar.setVisible(true);
    panelJuego.add(mar);
    panelJuego.setVisible(true);
    listoBTN.setVisible(true);
    presentacion();
    }//GEN-LAST:event_RUBTNActionPerformed

    private void listoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoBTNActionPerformed
    for(int i=0;i<5;i++){
    boolean val=false;
    while(val==false){
    int x=(int)(Math.random()*10);
    int y=(int)(Math.random()*10);
    if(Batalla.Barcos[x][y]==0)
    {
    Batalla.Barcos[x][y]=2;
    Batalla.colocarBarCom();
    val=true;
    }
    }
    }
    panel_instrucciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Consola :"));
    panel_instrucciones.setBackground(Color.WHITE);
    area.setBackground(Color.WHITE);
    area.setForeground(Color.magenta);
    area.setText("");
    panelJuego.remove(mar);
    panelJuego.setVisible(false);
    mar=new MarBatalla();
    mar.setVisible(true);
    panelJuego.add(mar);
    panelJuego.setVisible(true);
    listoBTN.setEnabled(false);
    listoBTN.setText("En juego");
    RUBTN.setVisible(false);
    }//GEN-LAST:event_listoBTNActionPerformed
    public static void finalizar(){
    panelJuego.remove(mar);
    panelJuego.setVisible(false);
    mar=new MarFinal();
    mar.setVisible(true);
    panelJuego.add(mar);
    panelJuego.setVisible(true);
    listoBTN.setVisible(false);
    RUBTN.setText("Jugar de nuevo");
    RUBTN.setVisible(true);
    listoBTN.setEnabled(true);
    listoBTN.setText("Listo !");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton RUBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JButton listoBTN;
    private static javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panel_instrucciones;
    // End of variables declaration//GEN-END:variables
}
